#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
# with a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

while echo "To infinity and beyond"; do
  sleep 2
  trap 'echo "I am invincible"' SIGTERM
done
